use std::path::Path;
use std::io::{BufRead, BufReader, Write};
use crate::error::AppError;

pub fn import_dotenv(path: &Path) -> Result<Vec<(String, String, String, String)>, AppError> {
    let file = std::fs::File::open(path)
        .map_err(|e| AppError::Import(format!("Failed to open .env file: {}", e)))?;
    let reader = BufReader::new(file);
    let mut keys = Vec::new();

    for line in reader.lines() {
        let line = line.map_err(|e| AppError::Import(format!("Failed to read line: {}", e)))?;
        let line = line.trim();

        // Skip comments and empty lines
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        if let Some((name, value)) = line.split_once('=') {
            let name = name.trim().to_string();
            let mut value = value.trim().to_string();

            // Remove surrounding quotes
            if (value.starts_with('"') && value.ends_with('"'))
                || (value.starts_with('\'') && value.ends_with('\''))
            {
                value = value[1..value.len() - 1].to_string();
            }

            // Infer provider from name
            let provider = infer_provider(&name);

            keys.push((name, provider, "ApiKey".to_string(), value));
        }
    }
    Ok(keys)
}

pub fn export_dotenv(path: &Path, keys: &[(String, String, String, String)]) -> Result<(), AppError> {
    let mut file = std::fs::File::create(path)
        .map_err(|e| AppError::Export(format!("Failed to create .env file: {}", e)))?;

    writeln!(file, "# Generated by apikey_etorer")
        .map_err(|e| AppError::Export(format!("Failed to write: {}", e)))?;
    writeln!(file, "# WARNING: This file contains sensitive information!")
        .map_err(|e| AppError::Export(format!("Failed to write: {}", e)))?;

    for (name, _provider, _key_type, value) in keys {
        // Convert key name to ENV_VAR format
        let env_name = name.to_uppercase().replace('-', "_").replace(' ', "_");

        writeln!(file, "{}=\"{}\"", env_name, value)
            .map_err(|e| AppError::Export(format!("Failed to write: {}", e)))?;
    }
    Ok(())
}

fn infer_provider(name: &str) -> String {
    let upper = name.to_uppercase();
    if upper.contains("OPENAI") {
        "OpenAI".to_string()
    } else if upper.contains("AWS") {
        "AWS".to_string()
    } else if upper.contains("GITHUB") {
        "GitHub".to_string()
    } else if upper.contains("GOOGLE") {
        "Google Cloud".to_string()
    } else if upper.contains("AZURE") {
        "Azure".to_string()
    } else {
        "Unknown".to_string()
    }
}